### ISSUE TITLE
Android Scroll

### ISSUE THREAD

**Issue by xopenex** [smelliott100/SarTechTools#11]
Screen does not scroll down on pages where content is longer than display area. Seems to be on every page except for the contacts page.

**Comment by elliottshane** [comment]
Do you have the font set larger than the default for  you device?  What kind of device do you have?

**Comment by Skittles4R32** [comment]
When entering data and phone keyboard pops up on screen to enter numbers into waypoint calculator, the screen does not account for this in display field, the keyboard covers the field into which the numbers are being entered, I have to clear the keyboard in order to see the field/numbers I am entering

**Comment by xopenex** [comment]
Samsung Galaxy S10+. I believe my font size, style, etc. Is default. It looks like the icon sizes have changed. I dont have a scrollable page to test currently. Length wise everything is currently fitting on one page.

**Comment by elliottshane** [comment]
location Calculator

**Comment by elliottshane** [comment]
@Skittles4R32 which field? what version of android do you have?  or do you have ios?

**Comment by Skittles4R32** [comment]
When I was entering UTMs the field didnt scroll up so I could see the field
I was entering the numbers.  I have android samsung galaxy s5

**Comment by elliottshane** [comment]
found the fix.  Will Post in next version thisafternoon.
